// Centralized SEO data for programmatic pages

export const industries = {
  ecommerce: {
    name: 'E-commerce',
    title: 'E-commerce Accessibility Compliance',
    description: 'Ensure your online store is accessible to all customers. WCAG 2.1 AA compliance for e-commerce websites.',
    hero: 'Make your online store accessible to 1 billion+ potential customers',
    painPoints: [
      'Product images without alt text exclude blind shoppers',
      'Inaccessible checkout flows cause cart abandonment',
      'Color-only status indicators confuse colorblind users',
      'Keyboard-inaccessible menus prevent navigation',
    ],
    stats: {
      marketSize: '$6.3T',
      disabledSpending: '$13B',
      lawsuitRisk: '73%',
    },
    regulations: ['EAA (June 2025)', 'ADA Title III', 'AODA (Canada)'],
  },
  healthcare: {
    name: 'Healthcare',
    title: 'Healthcare Website Accessibility',
    description: 'HIPAA and WCAG compliant healthcare websites. Accessible patient portals and medical information.',
    hero: 'Accessible healthcare websites save lives',
    painPoints: [
      'Inaccessible appointment booking excludes disabled patients',
      'Medical forms without labels create dangerous errors',
      'Low contrast text is unreadable for elderly patients',
      'Videos without captions exclude deaf patients',
    ],
    stats: {
      marketSize: '$12.2T',
      disabledSpending: '$490B',
      lawsuitRisk: '89%',
    },
    regulations: ['Section 508', 'ADA', 'HIPAA', 'EAA'],
  },
  finance: {
    name: 'Finance',
    title: 'Financial Services Accessibility',
    description: 'Accessible banking and financial websites. WCAG compliance for fintech and financial institutions.',
    hero: 'Financial inclusion starts with accessible websites',
    painPoints: [
      'Complex tables without proper headers confuse screen readers',
      'Time-limited sessions lock out users who need more time',
      'Security CAPTCHAs exclude blind users',
      'PDF statements are often completely inaccessible',
    ],
    stats: {
      marketSize: '$28.5T',
      disabledSpending: '$1.2T',
      lawsuitRisk: '82%',
    },
    regulations: ['EAA', 'ADA', 'Section 508', 'WCAG 2.1 AA'],
  },
  banking: {
    name: 'Banking',
    title: 'Banking Website Accessibility',
    description: 'Accessible online banking and mobile apps. WCAG compliance for banks and credit unions.',
    hero: 'Every customer deserves equal access to banking',
    painPoints: [
      'Account dashboards with poor keyboard navigation',
      'Transfer forms without proper error messages',
      'Mobile banking apps lacking screen reader support',
      'Authentication flows that exclude disabled users',
    ],
    stats: {
      marketSize: '$8.4T',
      disabledSpending: '$645B',
      lawsuitRisk: '85%',
    },
    regulations: ['EAA', 'ADA', 'Section 508', 'AODA'],
  },
  insurance: {
    name: 'Insurance',
    title: 'Insurance Website Accessibility',
    description: 'Accessible insurance quotes and policy management. WCAG compliance for insurance providers.',
    hero: 'Accessible insurance websites build customer trust',
    painPoints: [
      'Quote calculators with inaccessible form controls',
      'Policy documents in inaccessible PDF format',
      'Claims processes with time limits',
      'Complex comparison tables without proper markup',
    ],
    stats: {
      marketSize: '$6.3T',
      disabledSpending: '$490B',
      lawsuitRisk: '76%',
    },
    regulations: ['EAA', 'ADA', 'State regulations'],
  },
  education: {
    name: 'Education',
    title: 'Educational Website Accessibility',
    description: 'Accessible learning management systems and educational content. WCAG compliance for schools and universities.',
    hero: 'Education should be accessible to every learner',
    painPoints: [
      'Video lectures without captions or transcripts',
      'Interactive content requiring mouse-only interaction',
      'PDF textbooks and materials that are inaccessible',
      'LMS platforms with poor screen reader support',
    ],
    stats: {
      marketSize: '$7.3T',
      disabledSpending: '$285B',
      lawsuitRisk: '91%',
    },
    regulations: ['Section 504', 'ADA', 'IDEA', 'EAA'],
  },
  government: {
    name: 'Government',
    title: 'Government Website Accessibility',
    description: 'Section 508 and WCAG compliant government websites. Accessible public services for all citizens.',
    hero: 'Government services must be accessible to all citizens',
    painPoints: [
      'Complex forms for benefits and services',
      'Emergency information in inaccessible formats',
      'Public meeting videos without captions',
      'Outdated PDF documents lacking accessibility',
    ],
    stats: {
      marketSize: 'N/A',
      disabledSpending: 'Public service',
      lawsuitRisk: '94%',
    },
    regulations: ['Section 508', 'ADA', 'WCAG 2.1 AA', 'EN 301 549'],
  },
  travel: {
    name: 'Travel',
    title: 'Travel Website Accessibility',
    description: 'Accessible booking systems and travel information. WCAG compliance for airlines, hotels, and travel agencies.',
    hero: 'Make travel accessible for everyone',
    painPoints: [
      'Complex booking flows with poor keyboard support',
      'Interactive maps without text alternatives',
      'Time-limited booking sessions',
      'Seat selection interfaces excluding screen reader users',
    ],
    stats: {
      marketSize: '$9.9T',
      disabledSpending: '$58B',
      lawsuitRisk: '79%',
    },
    regulations: ['ADA', 'ACAA', 'EAA', 'WCAG 2.1 AA'],
  },
  retail: {
    name: 'Retail',
    title: 'Retail Website Accessibility',
    description: 'Accessible retail websites and online catalogs. WCAG compliance for retail businesses.',
    hero: 'Inclusive retail experiences drive loyalty',
    painPoints: [
      'Product filtering with inaccessible controls',
      'Size/color selectors without proper labels',
      'Store locator maps without text alternatives',
      'Promotional banners blocking content',
    ],
    stats: {
      marketSize: '$5.5T',
      disabledSpending: '$8B',
      lawsuitRisk: '71%',
    },
    regulations: ['ADA', 'EAA', 'AODA', 'WCAG 2.1 AA'],
  },
  media: {
    name: 'Media',
    title: 'Media Website Accessibility',
    description: 'Accessible news and media websites. WCAG compliance for publishers and content creators.',
    hero: 'Information access is a fundamental right',
    painPoints: [
      'Auto-playing videos disrupting screen readers',
      'Articles with poor heading structure',
      'Image-heavy layouts without alt text',
      'Paywalls creating accessibility barriers',
    ],
    stats: {
      marketSize: '$2.3T',
      disabledSpending: '$175B',
      lawsuitRisk: '68%',
    },
    regulations: ['ADA', 'EAA', 'CVAA', 'WCAG 2.1 AA'],
  },
  technology: {
    name: 'Technology',
    title: 'Tech Company Website Accessibility',
    description: 'Accessible SaaS platforms and tech products. WCAG compliance for technology companies.',
    hero: 'Tech companies should lead in accessibility',
    painPoints: [
      'Complex dashboards with poor screen reader support',
      'Documentation lacking accessibility',
      'Demo videos without captions',
      'Sign-up flows excluding disabled users',
    ],
    stats: {
      marketSize: '$5.3T',
      disabledSpending: '$412B',
      lawsuitRisk: '65%',
    },
    regulations: ['ADA', 'EAA', 'Section 508', 'VPAT requirements'],
  },
  legal: {
    name: 'Legal',
    title: 'Law Firm Website Accessibility',
    description: 'Accessible law firm websites and legal resources. WCAG compliance for legal services.',
    hero: 'Legal services should be accessible to all',
    painPoints: [
      'Contact forms without proper labels',
      'Case study content in inaccessible formats',
      'Attorney profiles lacking proper structure',
      'Legal document libraries in inaccessible PDFs',
    ],
    stats: {
      marketSize: '$1.1T',
      disabledSpending: '$85B',
      lawsuitRisk: '72%',
    },
    regulations: ['ADA', 'EAA', 'State bar requirements'],
  },
  'real-estate': {
    name: 'Real Estate',
    title: 'Real Estate Website Accessibility',
    description: 'Accessible property listings and real estate websites. WCAG compliance for real estate agencies.',
    hero: 'Everyone deserves to find their dream home',
    painPoints: [
      'Property search filters with poor accessibility',
      'Virtual tours excluding screen reader users',
      'Map-based searches without alternatives',
      'Image galleries without proper descriptions',
    ],
    stats: {
      marketSize: '$3.7T',
      disabledSpending: '$287B',
      lawsuitRisk: '67%',
    },
    regulations: ['Fair Housing Act', 'ADA', 'EAA'],
  },
  automotive: {
    name: 'Automotive',
    title: 'Automotive Website Accessibility',
    description: 'Accessible car dealership and manufacturer websites. WCAG compliance for the automotive industry.',
    hero: 'Car buying should be accessible to everyone',
    painPoints: [
      'Vehicle configurators with poor keyboard support',
      'Comparison tools lacking accessibility',
      'Financing calculators with inaccessible forms',
      '360° vehicle views without alternatives',
    ],
    stats: {
      marketSize: '$2.7T',
      disabledSpending: '$209B',
      lawsuitRisk: '69%',
    },
    regulations: ['ADA', 'EAA', 'WCAG 2.1 AA'],
  },
  hospitality: {
    name: 'Hospitality',
    title: 'Hospitality Website Accessibility',
    description: 'Accessible hotel and restaurant websites. WCAG compliance for the hospitality industry.',
    hero: 'Welcoming guests starts with an accessible website',
    painPoints: [
      'Room booking with accessibility options hidden',
      'Menu PDFs that are completely inaccessible',
      'Reservation systems with time limits',
      'Photo galleries without descriptions',
    ],
    stats: {
      marketSize: '$4.7T',
      disabledSpending: '$364B',
      lawsuitRisk: '74%',
    },
    regulations: ['ADA', 'EAA', 'WCAG 2.1 AA'],
  },
  nonprofit: {
    name: 'Nonprofit',
    title: 'Nonprofit Website Accessibility',
    description: 'Accessible nonprofit and charity websites. WCAG compliance for mission-driven organizations.',
    hero: 'Your mission deserves to reach everyone',
    painPoints: [
      'Donation forms with accessibility barriers',
      'Event registration excluding disabled supporters',
      'Impact reports in inaccessible formats',
      'Volunteer sign-up forms lacking labels',
    ],
    stats: {
      marketSize: '$2.5T',
      disabledSpending: '$194B',
      lawsuitRisk: '58%',
    },
    regulations: ['ADA', 'EAA', 'Section 508 (for federal grantees)'],
  },
  saas: {
    name: 'SaaS',
    title: 'SaaS Platform Accessibility',
    description: 'Accessible software-as-a-service platforms. WCAG compliance for cloud applications.',
    hero: 'Accessible SaaS is a competitive advantage',
    painPoints: [
      'Complex dashboards lacking keyboard navigation',
      'Data visualizations without text alternatives',
      'Settings panels with poor focus management',
      'Notification systems disrupting screen readers',
    ],
    stats: {
      marketSize: '$195B',
      disabledSpending: '$15B',
      lawsuitRisk: '61%',
    },
    regulations: ['ADA', 'EAA', 'VPAT requirements', 'Section 508'],
  },
  telecommunications: {
    name: 'Telecommunications',
    title: 'Telecom Website Accessibility',
    description: 'Accessible telecommunications websites. WCAG compliance for phone and internet providers.',
    hero: 'Communication services must be universally accessible',
    painPoints: [
      'Plan comparison tools with poor accessibility',
      'Account management portals lacking keyboard support',
      'Coverage maps without text alternatives',
      'Billing statements in inaccessible formats',
    ],
    stats: {
      marketSize: '$1.8T',
      disabledSpending: '$139B',
      lawsuitRisk: '77%',
    },
    regulations: ['ADA', 'Section 255', 'CVAA', 'EAA'],
  },
  manufacturing: {
    name: 'Manufacturing',
    title: 'Manufacturing Website Accessibility',
    description: 'Accessible B2B manufacturing websites. WCAG compliance for industrial companies.',
    hero: 'Industrial websites need industrial-strength accessibility',
    painPoints: [
      'Product catalogs with poor search accessibility',
      'Technical specifications in inaccessible PDFs',
      'Quote request forms lacking proper labels',
      'Dealer locator maps without alternatives',
    ],
    stats: {
      marketSize: '$16.6T',
      disabledSpending: '$1.3T',
      lawsuitRisk: '54%',
    },
    regulations: ['ADA', 'EAA', 'WCAG 2.1 AA'],
  },
  entertainment: {
    name: 'Entertainment',
    title: 'Entertainment Website Accessibility',
    description: 'Accessible entertainment and event websites. WCAG compliance for venues and ticketing.',
    hero: 'Entertainment should be for everyone',
    painPoints: [
      'Ticket purchasing flows with time limits',
      'Seat selection maps without alternatives',
      'Event videos without captions',
      'Venue information lacking accessibility details',
    ],
    stats: {
      marketSize: '$2.6T',
      disabledSpending: '$201B',
      lawsuitRisk: '70%',
    },
    regulations: ['ADA', 'EAA', 'CVAA', 'WCAG 2.1 AA'],
  },
  'food-beverage': {
    name: 'Food & Beverage',
    title: 'Food & Beverage Website Accessibility',
    description: 'Accessible restaurant and food service websites. WCAG compliance for F&B businesses.',
    hero: 'Every diner deserves an accessible menu',
    painPoints: [
      'Menus in image-only or inaccessible PDF format',
      'Online ordering systems with poor accessibility',
      'Reservation systems excluding disabled customers',
      'Allergen information not accessible',
    ],
    stats: {
      marketSize: '$8.1T',
      disabledSpending: '$627B',
      lawsuitRisk: '75%',
    },
    regulations: ['ADA', 'EAA', 'WCAG 2.1 AA'],
  },
  fashion: {
    name: 'Fashion',
    title: 'Fashion Website Accessibility',
    description: 'Accessible fashion and apparel websites. WCAG compliance for clothing retailers.',
    hero: 'Fashion is for everybody and every body',
    painPoints: [
      'Size guides in inaccessible formats',
      'Color swatches without text labels',
      'Lookbook galleries without descriptions',
      'Filtering systems with poor keyboard support',
    ],
    stats: {
      marketSize: '$1.7T',
      disabledSpending: '$132B',
      lawsuitRisk: '73%',
    },
    regulations: ['ADA', 'EAA', 'WCAG 2.1 AA'],
  },
  beauty: {
    name: 'Beauty',
    title: 'Beauty Website Accessibility',
    description: 'Accessible beauty and cosmetics websites. WCAG compliance for beauty brands.',
    hero: 'Beauty products should be accessible to all',
    painPoints: [
      'Shade selectors without text alternatives',
      'Virtual try-on tools excluding disabled users',
      'Product videos without audio descriptions',
      'Ingredient lists in inaccessible formats',
    ],
    stats: {
      marketSize: '$571B',
      disabledSpending: '$44B',
      lawsuitRisk: '68%',
    },
    regulations: ['ADA', 'EAA', 'WCAG 2.1 AA'],
  },
  sports: {
    name: 'Sports',
    title: 'Sports Website Accessibility',
    description: 'Accessible sports and athletics websites. WCAG compliance for teams and leagues.',
    hero: 'Sports content should reach every fan',
    painPoints: [
      'Live score updates inaccessible to screen readers',
      'Ticket purchasing with poor accessibility',
      'Statistics tables without proper markup',
      'Video highlights without captions',
    ],
    stats: {
      marketSize: '$620B',
      disabledSpending: '$48B',
      lawsuitRisk: '66%',
    },
    regulations: ['ADA', 'EAA', 'WCAG 2.1 AA'],
  },
  news: {
    name: 'News',
    title: 'News Website Accessibility',
    description: 'Accessible news and journalism websites. WCAG compliance for news publishers.',
    hero: 'Everyone deserves access to the news',
    painPoints: [
      'Breaking news alerts disrupting screen readers',
      'Articles with poor heading hierarchy',
      'Photo essays without descriptions',
      'Paywalls creating accessibility barriers',
    ],
    stats: {
      marketSize: '$181B',
      disabledSpending: '$14B',
      lawsuitRisk: '64%',
    },
    regulations: ['ADA', 'EAA', 'WCAG 2.1 AA'],
  },
  publishing: {
    name: 'Publishing',
    title: 'Publishing Website Accessibility',
    description: 'Accessible publishing and media websites. WCAG compliance for publishers.',
    hero: 'Published content should be universally accessible',
    painPoints: [
      'E-books in inaccessible formats',
      'Magazine layouts with poor reading order',
      'Subscription flows excluding disabled readers',
      'Archives lacking accessibility',
    ],
    stats: {
      marketSize: '$129B',
      disabledSpending: '$10B',
      lawsuitRisk: '62%',
    },
    regulations: ['ADA', 'EAA', 'WCAG 2.1 AA', 'Marrakesh Treaty'],
  },
} as const;

export const platforms = {
  shopify: {
    name: 'Shopify',
    title: 'Shopify Accessibility Compliance',
    description: 'Make your Shopify store WCAG 2.1 AA compliant. Fix accessibility issues in Shopify themes.',
    hero: 'Your Shopify store can be fully accessible',
    commonIssues: [
      'Theme color contrast violations',
      'Missing form labels in checkout',
      'Product images without alt text',
      'Keyboard-inaccessible mega menus',
      'Focus indicators removed by themes',
    ],
    marketShare: '28%',
    avgIssues: 47,
  },
  wordpress: {
    name: 'WordPress',
    title: 'WordPress Accessibility Compliance',
    description: 'Make your WordPress site WCAG 2.1 AA compliant. Accessibility for WordPress themes and plugins.',
    hero: 'Accessible WordPress sites are possible',
    commonIssues: [
      'Plugin conflicts causing accessibility issues',
      'Theme accessibility varies widely',
      'Media library images lacking alt text',
      'Contact form plugins with poor accessibility',
      'Page builders creating inaccessible markup',
    ],
    marketShare: '43%',
    avgIssues: 52,
  },
  wix: {
    name: 'Wix',
    title: 'Wix Accessibility Compliance',
    description: 'Make your Wix website WCAG 2.1 AA compliant. Accessibility solutions for Wix sites.',
    hero: 'Your Wix site can meet accessibility standards',
    commonIssues: [
      'Limited control over HTML structure',
      'Image alt text management challenges',
      'Animation effects causing issues',
      'Mobile menu accessibility problems',
      'Form accessibility limitations',
    ],
    marketShare: '7%',
    avgIssues: 61,
  },
  squarespace: {
    name: 'Squarespace',
    title: 'Squarespace Accessibility Compliance',
    description: 'Make your Squarespace site WCAG 2.1 AA compliant. Accessibility for Squarespace templates.',
    hero: 'Beautiful and accessible Squarespace sites',
    commonIssues: [
      'Template contrast issues',
      'Gallery accessibility limitations',
      'Limited heading structure control',
      'Form field labeling challenges',
      'Navigation accessibility varies by template',
    ],
    marketShare: '4%',
    avgIssues: 44,
  },
  webflow: {
    name: 'Webflow',
    title: 'Webflow Accessibility Compliance',
    description: 'Make your Webflow site WCAG 2.1 AA compliant. Best practices for accessible Webflow design.',
    hero: 'Design freedom with accessibility compliance',
    commonIssues: [
      'Custom interactions lacking accessibility',
      'CMS content missing alt text',
      'Complex animations causing issues',
      'Form accessibility requiring manual work',
      'Focus states need manual implementation',
    ],
    marketShare: '2%',
    avgIssues: 38,
  },
  magento: {
    name: 'Magento',
    title: 'Magento Accessibility Compliance',
    description: 'Make your Magento store WCAG 2.1 AA compliant. Accessibility for Adobe Commerce.',
    hero: 'Enterprise-grade accessible e-commerce',
    commonIssues: [
      'Complex checkout flow accessibility',
      'Third-party extension issues',
      'Product filtering accessibility',
      'Search functionality challenges',
      'Account management accessibility',
    ],
    marketShare: '2%',
    avgIssues: 58,
  },
  bigcommerce: {
    name: 'BigCommerce',
    title: 'BigCommerce Accessibility Compliance',
    description: 'Make your BigCommerce store WCAG 2.1 AA compliant. Accessibility solutions for BigCommerce.',
    hero: 'Accessible BigCommerce stores convert better',
    commonIssues: [
      'Theme accessibility varies widely',
      'Product variant selectors',
      'Cart and checkout accessibility',
      'Search and filtering issues',
      'Mobile navigation problems',
    ],
    marketShare: '3%',
    avgIssues: 45,
  },
  woocommerce: {
    name: 'WooCommerce',
    title: 'WooCommerce Accessibility Compliance',
    description: 'Make your WooCommerce store WCAG 2.1 AA compliant. Accessibility for WordPress e-commerce.',
    hero: 'Your WooCommerce store can serve everyone',
    commonIssues: [
      'Plugin compatibility issues',
      'Theme-dependent accessibility',
      'Checkout flow challenges',
      'Product gallery accessibility',
      'Cart updates lacking announcements',
    ],
    marketShare: '8%',
    avgIssues: 49,
  },
  drupal: {
    name: 'Drupal',
    title: 'Drupal Accessibility Compliance',
    description: 'Make your Drupal site WCAG 2.1 AA compliant. Accessibility best practices for Drupal.',
    hero: 'Drupal has strong accessibility foundations',
    commonIssues: [
      'Module accessibility varies',
      'Theme implementation issues',
      'WYSIWYG content accessibility',
      'Views output accessibility',
      'Custom development oversights',
    ],
    marketShare: '2%',
    avgIssues: 35,
  },
  joomla: {
    name: 'Joomla',
    title: 'Joomla Accessibility Compliance',
    description: 'Make your Joomla site WCAG 2.1 AA compliant. Accessibility solutions for Joomla.',
    hero: 'Accessible Joomla sites are achievable',
    commonIssues: [
      'Extension accessibility issues',
      'Template accessibility varies',
      'Editor content challenges',
      'Menu accessibility problems',
      'Form component issues',
    ],
    marketShare: '1%',
    avgIssues: 51,
  },
  ghost: {
    name: 'Ghost',
    title: 'Ghost Accessibility Compliance',
    description: 'Make your Ghost publication WCAG 2.1 AA compliant. Accessibility for Ghost themes.',
    hero: 'Accessible publishing with Ghost',
    commonIssues: [
      'Theme contrast issues',
      'Image alt text management',
      'Card content accessibility',
      'Navigation accessibility',
      'Membership portal accessibility',
    ],
    marketShare: '<1%',
    avgIssues: 32,
  },
  contentful: {
    name: 'Contentful',
    title: 'Contentful Accessibility Compliance',
    description: 'Accessible content delivery with Contentful. WCAG compliance for headless CMS.',
    hero: 'Structured content enables accessibility',
    commonIssues: [
      'Alt text workflow enforcement',
      'Rich text accessibility',
      'Frontend implementation varies',
      'Preview functionality accessibility',
      'Asset management for accessibility',
    ],
    marketShare: '<1%',
    avgIssues: 28,
  },
  strapi: {
    name: 'Strapi',
    title: 'Strapi Accessibility Compliance',
    description: 'Accessible content management with Strapi. WCAG compliance for Strapi frontends.',
    hero: 'Build accessible experiences with Strapi',
    commonIssues: [
      'Frontend implementation responsibility',
      'Content modeling for accessibility',
      'Media library alt text',
      'API response accessibility data',
      'Admin panel accessibility',
    ],
    marketShare: '<1%',
    avgIssues: 25,
  },
  sanity: {
    name: 'Sanity',
    title: 'Sanity Accessibility Compliance',
    description: 'Accessible content with Sanity CMS. WCAG compliance for Sanity-powered sites.',
    hero: 'Sanity enables accessible content workflows',
    commonIssues: [
      'Schema design for accessibility',
      'Image hotspot alt text',
      'Portable text accessibility',
      'Frontend implementation varies',
      'Preview mode accessibility',
    ],
    marketShare: '<1%',
    avgIssues: 24,
  },
  hubspot: {
    name: 'HubSpot',
    title: 'HubSpot Accessibility Compliance',
    description: 'Make your HubSpot site WCAG 2.1 AA compliant. Accessibility for HubSpot CMS.',
    hero: 'Accessible marketing starts with HubSpot',
    commonIssues: [
      'Template accessibility varies',
      'Form module accessibility',
      'CTA button accessibility',
      'Blog listing accessibility',
      'Landing page builder issues',
    ],
    marketShare: '1%',
    avgIssues: 41,
  },
  salesforce: {
    name: 'Salesforce',
    title: 'Salesforce Commerce Accessibility',
    description: 'Make your Salesforce Commerce site WCAG 2.1 AA compliant. Accessibility for SFCC.',
    hero: 'Enterprise accessibility with Salesforce',
    commonIssues: [
      'Complex component accessibility',
      'SFRA cartridge issues',
      'Checkout flow challenges',
      'Search and filter accessibility',
      'Account management accessibility',
    ],
    marketShare: '2%',
    avgIssues: 54,
  },
  prestashop: {
    name: 'PrestaShop',
    title: 'PrestaShop Accessibility Compliance',
    description: 'Make your PrestaShop store WCAG 2.1 AA compliant. Accessibility for PrestaShop.',
    hero: 'Accessible PrestaShop stores for Europe',
    commonIssues: [
      'Theme accessibility varies widely',
      'Module accessibility issues',
      'Checkout flow challenges',
      'Product page accessibility',
      'Search functionality problems',
    ],
    marketShare: '1%',
    avgIssues: 56,
  },
  opencart: {
    name: 'OpenCart',
    title: 'OpenCart Accessibility Compliance',
    description: 'Make your OpenCart store WCAG 2.1 AA compliant. Accessibility solutions for OpenCart.',
    hero: 'Accessible OpenCart stores are possible',
    commonIssues: [
      'Default theme issues',
      'Extension accessibility varies',
      'Checkout accessibility',
      'Product options accessibility',
      'Category navigation problems',
    ],
    marketShare: '<1%',
    avgIssues: 62,
  },
  volusion: {
    name: 'Volusion',
    title: 'Volusion Accessibility Compliance',
    description: 'Make your Volusion store WCAG 2.1 AA compliant. Accessibility for Volusion sites.',
    hero: 'Accessible Volusion stores serve everyone',
    commonIssues: [
      'Template accessibility issues',
      'Checkout flow problems',
      'Product display accessibility',
      'Navigation accessibility',
      'Form labeling challenges',
    ],
    marketShare: '<1%',
    avgIssues: 58,
  },
  shift4shop: {
    name: 'Shift4Shop',
    title: 'Shift4Shop Accessibility Compliance',
    description: 'Make your Shift4Shop store WCAG 2.1 AA compliant. Accessibility for 3dcart.',
    hero: 'Accessible Shift4Shop stores convert better',
    commonIssues: [
      'Theme accessibility varies',
      'Checkout accessibility issues',
      'Product filtering problems',
      'Mobile navigation challenges',
      'Form accessibility issues',
    ],
    marketShare: '<1%',
    avgIssues: 55,
  },
  ecwid: {
    name: 'Ecwid',
    title: 'Ecwid Accessibility Compliance',
    description: 'Make your Ecwid store WCAG 2.1 AA compliant. Accessibility for embedded stores.',
    hero: 'Accessible Ecwid stores anywhere',
    commonIssues: [
      'Widget embedding accessibility',
      'Checkout flow issues',
      'Product display accessibility',
      'Cart popup accessibility',
      'Mobile responsiveness issues',
    ],
    marketShare: '<1%',
    avgIssues: 48,
  },
  weebly: {
    name: 'Weebly',
    title: 'Weebly Accessibility Compliance',
    description: 'Make your Weebly site WCAG 2.1 AA compliant. Accessibility solutions for Weebly.',
    hero: 'Accessible Weebly sites are achievable',
    commonIssues: [
      'Theme accessibility limitations',
      'Drag-drop editor challenges',
      'Form element accessibility',
      'Image alt text management',
      'Navigation structure issues',
    ],
    marketShare: '<1%',
    avgIssues: 53,
  },
  godaddy: {
    name: 'GoDaddy',
    title: 'GoDaddy Website Accessibility',
    description: 'Make your GoDaddy site WCAG 2.1 AA compliant. Accessibility for GoDaddy websites.',
    hero: 'Accessible GoDaddy sites for small business',
    commonIssues: [
      'Template accessibility varies',
      'Builder limitations',
      'Form accessibility issues',
      'Image management challenges',
      'Mobile menu problems',
    ],
    marketShare: '1%',
    avgIssues: 57,
  },
  notion: {
    name: 'Notion',
    title: 'Notion Website Accessibility',
    description: 'Accessibility for Notion-published websites. WCAG compliance for Notion pages.',
    hero: 'Accessible documentation with Notion',
    commonIssues: [
      'Limited customization options',
      'Database view accessibility',
      'Toggle block accessibility',
      'Embedded content issues',
      'Navigation structure limitations',
    ],
    marketShare: '<1%',
    avgIssues: 36,
  },
} as const;

export const euCountries = {
  germany: {
    name: 'Germany',
    nativeName: 'Deutschland',
    title: 'EAA Compliance in Germany',
    description: 'European Accessibility Act compliance for German businesses. WCAG requirements for Germany.',
    deadline: 'June 28, 2025',
    localLaw: 'Barrierefreiheitsstärkungsgesetz (BFSG)',
    penalties: 'Up to €100,000 fines',
    population: '83M',
    gdp: '$4.2T',
  },
  france: {
    name: 'France',
    nativeName: 'France',
    title: 'EAA Compliance in France',
    description: 'European Accessibility Act compliance for French businesses. WCAG requirements for France.',
    deadline: 'June 28, 2025',
    localLaw: 'Loi pour une République numérique',
    penalties: 'Up to €50,000 fines',
    population: '67M',
    gdp: '$2.8T',
  },
  spain: {
    name: 'Spain',
    nativeName: 'España',
    title: 'EAA Compliance in Spain',
    description: 'European Accessibility Act compliance for Spanish businesses. WCAG requirements for Spain.',
    deadline: 'June 28, 2025',
    localLaw: 'Real Decreto 1112/2018',
    penalties: 'Up to €150,000 fines',
    population: '47M',
    gdp: '$1.4T',
  },
  italy: {
    name: 'Italy',
    nativeName: 'Italia',
    title: 'EAA Compliance in Italy',
    description: 'European Accessibility Act compliance for Italian businesses. WCAG requirements for Italy.',
    deadline: 'June 28, 2025',
    localLaw: 'Legge Stanca (L. 4/2004)',
    penalties: 'Up to €100,000 fines',
    population: '60M',
    gdp: '$2.1T',
  },
  netherlands: {
    name: 'Netherlands',
    nativeName: 'Nederland',
    title: 'EAA Compliance in Netherlands',
    description: 'European Accessibility Act compliance for Dutch businesses. WCAG requirements for Netherlands.',
    deadline: 'June 28, 2025',
    localLaw: 'Tijdelijk besluit digitale toegankelijkheid',
    penalties: 'Administrative enforcement',
    population: '17M',
    gdp: '$1.0T',
  },
  belgium: {
    name: 'Belgium',
    nativeName: 'België/Belgique',
    title: 'EAA Compliance in Belgium',
    description: 'European Accessibility Act compliance for Belgian businesses. WCAG requirements for Belgium.',
    deadline: 'June 28, 2025',
    localLaw: 'Federal/Regional accessibility laws',
    penalties: 'Varies by region',
    population: '11M',
    gdp: '$0.6T',
  },
  austria: {
    name: 'Austria',
    nativeName: 'Österreich',
    title: 'EAA Compliance in Austria',
    description: 'European Accessibility Act compliance for Austrian businesses. WCAG requirements for Austria.',
    deadline: 'June 28, 2025',
    localLaw: 'Bundes-Behindertengleichstellungsgesetz',
    penalties: 'Up to €100,000 fines',
    population: '9M',
    gdp: '$0.5T',
  },
  sweden: {
    name: 'Sweden',
    nativeName: 'Sverige',
    title: 'EAA Compliance in Sweden',
    description: 'European Accessibility Act compliance for Swedish businesses. WCAG requirements for Sweden.',
    deadline: 'June 28, 2025',
    localLaw: 'Lag om tillgänglighet till digital offentlig service',
    penalties: 'Administrative sanctions',
    population: '10M',
    gdp: '$0.6T',
  },
  denmark: {
    name: 'Denmark',
    nativeName: 'Danmark',
    title: 'EAA Compliance in Denmark',
    description: 'European Accessibility Act compliance for Danish businesses. WCAG requirements for Denmark.',
    deadline: 'June 28, 2025',
    localLaw: 'Lov om tilgængelighed',
    penalties: 'Administrative enforcement',
    population: '6M',
    gdp: '$0.4T',
  },
  finland: {
    name: 'Finland',
    nativeName: 'Suomi',
    title: 'EAA Compliance in Finland',
    description: 'European Accessibility Act compliance for Finnish businesses. WCAG requirements for Finland.',
    deadline: 'June 28, 2025',
    localLaw: 'Laki digitaalisten palvelujen tarjoamisesta',
    penalties: 'Administrative sanctions',
    population: '5M',
    gdp: '$0.3T',
  },
  poland: {
    name: 'Poland',
    nativeName: 'Polska',
    title: 'EAA Compliance in Poland',
    description: 'European Accessibility Act compliance for Polish businesses. WCAG requirements for Poland.',
    deadline: 'June 28, 2025',
    localLaw: 'Ustawa o dostępności cyfrowej',
    penalties: 'Up to PLN 100,000',
    population: '38M',
    gdp: '$0.7T',
  },
  portugal: {
    name: 'Portugal',
    nativeName: 'Portugal',
    title: 'EAA Compliance in Portugal',
    description: 'European Accessibility Act compliance for Portuguese businesses. WCAG requirements for Portugal.',
    deadline: 'June 28, 2025',
    localLaw: 'Decreto-Lei n.º 83/2018',
    penalties: 'Administrative sanctions',
    population: '10M',
    gdp: '$0.3T',
  },
  ireland: {
    name: 'Ireland',
    nativeName: 'Éire',
    title: 'EAA Compliance in Ireland',
    description: 'European Accessibility Act compliance for Irish businesses. WCAG requirements for Ireland.',
    deadline: 'June 28, 2025',
    localLaw: 'European Union (Accessibility of Websites) Regulations 2020',
    penalties: 'Administrative enforcement',
    population: '5M',
    gdp: '$0.5T',
  },
  greece: {
    name: 'Greece',
    nativeName: 'Ελλάδα',
    title: 'EAA Compliance in Greece',
    description: 'European Accessibility Act compliance for Greek businesses. WCAG requirements for Greece.',
    deadline: 'June 28, 2025',
    localLaw: 'Law 4727/2020',
    penalties: 'Administrative sanctions',
    population: '11M',
    gdp: '$0.2T',
  },
  'czech-republic': {
    name: 'Czech Republic',
    nativeName: 'Česká republika',
    title: 'EAA Compliance in Czech Republic',
    description: 'European Accessibility Act compliance for Czech businesses. WCAG requirements for Czechia.',
    deadline: 'June 28, 2025',
    localLaw: 'Zákon o přístupnosti',
    penalties: 'Administrative sanctions',
    population: '11M',
    gdp: '$0.3T',
  },
  romania: {
    name: 'Romania',
    nativeName: 'România',
    title: 'EAA Compliance in Romania',
    description: 'European Accessibility Act compliance for Romanian businesses. WCAG requirements for Romania.',
    deadline: 'June 28, 2025',
    localLaw: 'Government Decision 1309/2020',
    penalties: 'Administrative sanctions',
    population: '19M',
    gdp: '$0.3T',
  },
  hungary: {
    name: 'Hungary',
    nativeName: 'Magyarország',
    title: 'EAA Compliance in Hungary',
    description: 'European Accessibility Act compliance for Hungarian businesses. WCAG requirements for Hungary.',
    deadline: 'June 28, 2025',
    localLaw: 'Government Decree 472/2020',
    penalties: 'Administrative sanctions',
    population: '10M',
    gdp: '$0.2T',
  },
  luxembourg: {
    name: 'Luxembourg',
    nativeName: 'Lëtzebuerg',
    title: 'EAA Compliance in Luxembourg',
    description: 'European Accessibility Act compliance for Luxembourg businesses. WCAG requirements for Luxembourg.',
    deadline: 'June 28, 2025',
    localLaw: 'Loi du 28 mai 2019',
    penalties: 'Administrative enforcement',
    population: '0.6M',
    gdp: '$0.1T',
  },
  slovakia: {
    name: 'Slovakia',
    nativeName: 'Slovensko',
    title: 'EAA Compliance in Slovakia',
    description: 'European Accessibility Act compliance for Slovak businesses. WCAG requirements for Slovakia.',
    deadline: 'June 28, 2025',
    localLaw: 'Act on accessibility of websites',
    penalties: 'Administrative sanctions',
    population: '5M',
    gdp: '$0.1T',
  },
  croatia: {
    name: 'Croatia',
    nativeName: 'Hrvatska',
    title: 'EAA Compliance in Croatia',
    description: 'European Accessibility Act compliance for Croatian businesses. WCAG requirements for Croatia.',
    deadline: 'June 28, 2025',
    localLaw: 'Pravilnik o pristupačnosti',
    penalties: 'Administrative sanctions',
    population: '4M',
    gdp: '$0.07T',
  },
  slovenia: {
    name: 'Slovenia',
    nativeName: 'Slovenija',
    title: 'EAA Compliance in Slovenia',
    description: 'European Accessibility Act compliance for Slovenian businesses. WCAG requirements for Slovenia.',
    deadline: 'June 28, 2025',
    localLaw: 'Zakon o dostopnosti',
    penalties: 'Administrative sanctions',
    population: '2M',
    gdp: '$0.06T',
  },
  lithuania: {
    name: 'Lithuania',
    nativeName: 'Lietuva',
    title: 'EAA Compliance in Lithuania',
    description: 'European Accessibility Act compliance for Lithuanian businesses. WCAG requirements for Lithuania.',
    deadline: 'June 28, 2025',
    localLaw: 'Law on Digital Accessibility',
    penalties: 'Administrative sanctions',
    population: '3M',
    gdp: '$0.07T',
  },
  latvia: {
    name: 'Latvia',
    nativeName: 'Latvija',
    title: 'EAA Compliance in Latvia',
    description: 'European Accessibility Act compliance for Latvian businesses. WCAG requirements for Latvia.',
    deadline: 'June 28, 2025',
    localLaw: 'Regulations on digital accessibility',
    penalties: 'Administrative sanctions',
    population: '2M',
    gdp: '$0.04T',
  },
  estonia: {
    name: 'Estonia',
    nativeName: 'Eesti',
    title: 'EAA Compliance in Estonia',
    description: 'European Accessibility Act compliance for Estonian businesses. WCAG requirements for Estonia.',
    deadline: 'June 28, 2025',
    localLaw: 'Digitaalse ligipääsetavuse nõuded',
    penalties: 'Administrative sanctions',
    population: '1M',
    gdp: '$0.04T',
  },
  bulgaria: {
    name: 'Bulgaria',
    nativeName: 'България',
    title: 'EAA Compliance in Bulgaria',
    description: 'European Accessibility Act compliance for Bulgarian businesses. WCAG requirements for Bulgaria.',
    deadline: 'June 28, 2025',
    localLaw: 'Ordinance on digital accessibility',
    penalties: 'Administrative sanctions',
    population: '7M',
    gdp: '$0.08T',
  },
  cyprus: {
    name: 'Cyprus',
    nativeName: 'Κύπρος',
    title: 'EAA Compliance in Cyprus',
    description: 'European Accessibility Act compliance for Cypriot businesses. WCAG requirements for Cyprus.',
    deadline: 'June 28, 2025',
    localLaw: 'Accessibility regulations',
    penalties: 'Administrative sanctions',
    population: '1M',
    gdp: '$0.03T',
  },
  malta: {
    name: 'Malta',
    nativeName: 'Malta',
    title: 'EAA Compliance in Malta',
    description: 'European Accessibility Act compliance for Maltese businesses. WCAG requirements for Malta.',
    deadline: 'June 28, 2025',
    localLaw: 'Accessibility of Websites Regulations',
    penalties: 'Administrative sanctions',
    population: '0.5M',
    gdp: '$0.02T',
  },
} as const;

export const wcagCriteria = {
  '1-1-1-non-text-content': {
    number: '1.1.1',
    name: 'Non-text Content',
    level: 'A',
    principle: 'Perceivable',
    guideline: 'Text Alternatives',
    description: 'All non-text content has a text alternative that serves the equivalent purpose.',
    whyItMatters: 'Screen reader users cannot perceive images, charts, or other visual content without text descriptions.',
    howToFix: [
      'Add descriptive alt text to all informative images',
      'Use empty alt="" for decorative images',
      'Provide text alternatives for charts and infographics',
      'Add captions and transcripts to audio/video content',
    ],
    commonViolations: [
      'Missing alt attributes on images',
      'Generic alt text like "image" or "photo"',
      'Alt text describing file names instead of content',
      'Missing descriptions for complex visualizations',
    ],
  },
  '1-3-1-info-and-relationships': {
    number: '1.3.1',
    name: 'Info and Relationships',
    level: 'A',
    principle: 'Perceivable',
    guideline: 'Adaptable',
    description: 'Information, structure, and relationships conveyed through presentation can be programmatically determined.',
    whyItMatters: 'Screen readers rely on proper HTML structure to convey relationships between content.',
    howToFix: [
      'Use semantic HTML elements (headings, lists, tables)',
      'Associate form labels with their controls',
      'Use proper table headers and structure',
      'Mark up regions with ARIA landmarks',
    ],
    commonViolations: [
      'Headings used for styling instead of structure',
      'Tables used for layout instead of data',
      'Form inputs without associated labels',
      'Lists created with line breaks instead of ul/ol',
    ],
  },
  '1-4-1-use-of-color': {
    number: '1.4.1',
    name: 'Use of Color',
    level: 'A',
    principle: 'Perceivable',
    guideline: 'Distinguishable',
    description: 'Color is not used as the only visual means of conveying information.',
    whyItMatters: 'Colorblind users and those with low vision cannot rely on color alone to understand content.',
    howToFix: [
      'Add text labels to color-coded information',
      'Use patterns or icons in addition to color',
      'Ensure links are distinguishable by more than color',
      'Add underlines or other visual indicators',
    ],
    commonViolations: [
      'Error messages indicated only by red color',
      'Required fields shown only with colored asterisks',
      'Charts using only color to differentiate data',
      'Links distinguished only by color from surrounding text',
    ],
  },
  '1-4-3-contrast-minimum': {
    number: '1.4.3',
    name: 'Contrast (Minimum)',
    level: 'AA',
    principle: 'Perceivable',
    guideline: 'Distinguishable',
    description: 'Text has a contrast ratio of at least 4.5:1 (3:1 for large text).',
    whyItMatters: 'Low contrast text is difficult to read for users with low vision or in bright environments.',
    howToFix: [
      'Check all text against background colors',
      'Use contrast checking tools during design',
      'Increase font size or weight for borderline cases',
      'Avoid text over images without sufficient contrast',
    ],
    commonViolations: [
      'Light gray text on white backgrounds',
      'Placeholder text with insufficient contrast',
      'Text over images without background overlay',
      'Disabled state text that fails contrast',
    ],
  },
  '1-4-11-non-text-contrast': {
    number: '1.4.11',
    name: 'Non-text Contrast',
    level: 'AA',
    principle: 'Perceivable',
    guideline: 'Distinguishable',
    description: 'UI components and graphical objects have a contrast ratio of at least 3:1.',
    whyItMatters: 'Users need to perceive interactive controls and meaningful graphics.',
    howToFix: [
      'Ensure button borders meet 3:1 contrast',
      'Check form field boundaries against backgrounds',
      'Verify icon contrast against their backgrounds',
      'Test focus indicators for sufficient contrast',
    ],
    commonViolations: [
      'Light gray input field borders',
      'Icons that blend into backgrounds',
      'Chart elements with low contrast',
      'Focus indicators that are barely visible',
    ],
  },
  '2-1-1-keyboard': {
    number: '2.1.1',
    name: 'Keyboard',
    level: 'A',
    principle: 'Operable',
    guideline: 'Keyboard Accessible',
    description: 'All functionality is available from a keyboard without requiring specific timings.',
    whyItMatters: 'Many users cannot use a mouse due to motor disabilities or assistive technology.',
    howToFix: [
      'Ensure all interactive elements are focusable',
      'Use native HTML elements where possible',
      'Add keyboard handlers to custom components',
      'Test entire workflows with keyboard only',
    ],
    commonViolations: [
      'Click-only event handlers without keyboard support',
      'Custom dropdowns that cannot be operated with keyboard',
      'Drag-and-drop without keyboard alternatives',
      'Hover-only tooltips and menus',
    ],
  },
  '2-1-2-no-keyboard-trap': {
    number: '2.1.2',
    name: 'No Keyboard Trap',
    level: 'A',
    principle: 'Operable',
    guideline: 'Keyboard Accessible',
    description: 'Keyboard focus can be moved away from any component using only a keyboard.',
    whyItMatters: 'Users can become stuck if focus cannot be moved away from a component.',
    howToFix: [
      'Test that Tab and Shift+Tab work correctly',
      'Ensure modal dialogs can be closed with Escape',
      'Verify focus management in custom components',
      'Test embedded content like iframes',
    ],
    commonViolations: [
      'Modal dialogs that trap focus incorrectly',
      'Embedded video players trapping keyboard',
      'Custom rich text editors',
      'Date pickers and other complex widgets',
    ],
  },
  '2-4-1-bypass-blocks': {
    number: '2.4.1',
    name: 'Bypass Blocks',
    level: 'A',
    principle: 'Operable',
    guideline: 'Navigable',
    description: 'A mechanism is available to bypass blocks of content repeated on multiple pages.',
    whyItMatters: 'Screen reader users should not have to navigate through repeated content on every page.',
    howToFix: [
      'Add a "Skip to main content" link',
      'Use proper heading hierarchy',
      'Implement ARIA landmark regions',
      'Ensure skip links are visible on focus',
    ],
    commonViolations: [
      'Missing skip navigation links',
      'Skip links that are permanently hidden',
      'Missing or incorrect landmark regions',
      'No heading structure on pages',
    ],
  },
  '2-4-2-page-titled': {
    number: '2.4.2',
    name: 'Page Titled',
    level: 'A',
    principle: 'Operable',
    guideline: 'Navigable',
    description: 'Web pages have titles that describe topic or purpose.',
    whyItMatters: 'Page titles help users identify and navigate between browser tabs.',
    howToFix: [
      'Use unique, descriptive page titles',
      'Include the page purpose and site name',
      'Update titles for single-page applications',
      'Follow a consistent title pattern',
    ],
    commonViolations: [
      'Generic titles like "Home" or "Welcome"',
      'Same title used for all pages',
      'Missing title elements',
      'SPA titles not updating on navigation',
    ],
  },
  '2-4-4-link-purpose': {
    number: '2.4.4',
    name: 'Link Purpose (In Context)',
    level: 'A',
    principle: 'Operable',
    guideline: 'Navigable',
    description: 'The purpose of each link can be determined from the link text or context.',
    whyItMatters: 'Users navigating by links need to understand where each link will take them.',
    howToFix: [
      'Use descriptive link text',
      'Avoid "click here" and "read more"',
      'Add aria-label for icon-only links',
      'Ensure context makes link purpose clear',
    ],
    commonViolations: [
      'Generic "click here" links',
      'Multiple "read more" links on a page',
      'Icon-only links without text alternatives',
      'Ambiguous link text like "here" or "this"',
    ],
  },
  '2-4-6-headings-and-labels': {
    number: '2.4.6',
    name: 'Headings and Labels',
    level: 'AA',
    principle: 'Operable',
    guideline: 'Navigable',
    description: 'Headings and labels describe topic or purpose.',
    whyItMatters: 'Clear headings and labels help users understand and navigate content.',
    howToFix: [
      'Write descriptive, unique headings',
      'Use clear, specific form labels',
      'Avoid generic headings like "Introduction"',
      'Make labels describe the expected input',
    ],
    commonViolations: [
      'Vague headings like "More Information"',
      'Form labels that do not describe the field',
      'Duplicate headings on the same page',
      'Labels that do not match input requirements',
    ],
  },
  '2-4-7-focus-visible': {
    number: '2.4.7',
    name: 'Focus Visible',
    level: 'AA',
    principle: 'Operable',
    guideline: 'Navigable',
    description: 'Any keyboard operable user interface has a visible focus indicator.',
    whyItMatters: 'Keyboard users need to see which element currently has focus.',
    howToFix: [
      'Never remove focus outlines without replacement',
      'Use visible, high-contrast focus indicators',
      'Ensure custom focus styles are clearly visible',
      'Test focus visibility in all color modes',
    ],
    commonViolations: [
      'CSS outline: none without replacement',
      'Low contrast focus indicators',
      'Focus indicators hidden by overlapping elements',
      'Inconsistent focus styles across components',
    ],
  },
  '3-1-1-language-of-page': {
    number: '3.1.1',
    name: 'Language of Page',
    level: 'A',
    principle: 'Understandable',
    guideline: 'Readable',
    description: 'The default human language of each page can be programmatically determined.',
    whyItMatters: 'Screen readers need to know the language to pronounce content correctly.',
    howToFix: [
      'Add lang attribute to the html element',
      'Use correct language codes (en, fr, de, etc.)',
      'Update language for multilingual sites',
      'Test with screen readers in different languages',
    ],
    commonViolations: [
      'Missing lang attribute on html',
      'Incorrect language code',
      'Language not matching actual content',
      'Missing lang on embedded content',
    ],
  },
  '3-2-1-on-focus': {
    number: '3.2.1',
    name: 'On Focus',
    level: 'A',
    principle: 'Understandable',
    guideline: 'Predictable',
    description: 'When any component receives focus, it does not initiate a change of context.',
    whyItMatters: 'Unexpected changes when focusing elements can disorient users.',
    howToFix: [
      'Avoid automatic form submission on focus',
      'Do not open new windows on focus',
      'Keep context stable when navigating with keyboard',
      'Use explicit user actions for context changes',
    ],
    commonViolations: [
      'Forms that submit when a field receives focus',
      'Links that open popups on focus',
      'Select menus that navigate on focus',
      'Dialogs that open when focusing elements',
    ],
  },
  '3-3-1-error-identification': {
    number: '3.3.1',
    name: 'Error Identification',
    level: 'A',
    principle: 'Understandable',
    guideline: 'Input Assistance',
    description: 'If an input error is detected, the item in error is identified and described in text.',
    whyItMatters: 'Users need to know what errors occurred and where to fix them.',
    howToFix: [
      'Identify the specific field with the error',
      'Describe the error in text (not just color)',
      'Associate error messages with form fields',
      'Announce errors to screen readers',
    ],
    commonViolations: [
      'Errors indicated only by color',
      'Generic error messages like "Invalid input"',
      'Errors not associated with specific fields',
      'Error messages not announced to screen readers',
    ],
  },
  '3-3-2-labels-or-instructions': {
    number: '3.3.2',
    name: 'Labels or Instructions',
    level: 'A',
    principle: 'Understandable',
    guideline: 'Input Assistance',
    description: 'Labels or instructions are provided when content requires user input.',
    whyItMatters: 'Users need to understand what information is expected in form fields.',
    howToFix: [
      'Provide visible labels for all inputs',
      'Include format hints (e.g., MM/DD/YYYY)',
      'Indicate required fields clearly',
      'Provide examples for complex inputs',
    ],
    commonViolations: [
      'Placeholder text used instead of labels',
      'Missing format instructions for dates/phones',
      'Required fields not clearly indicated',
      'Complex inputs without examples',
    ],
  },
  '4-1-1-parsing': {
    number: '4.1.1',
    name: 'Parsing',
    level: 'A',
    principle: 'Robust',
    guideline: 'Compatible',
    description: 'Elements have complete start and end tags, are nested properly, and do not contain duplicates.',
    whyItMatters: 'Valid HTML ensures consistent interpretation by browsers and assistive technologies.',
    howToFix: [
      'Validate HTML for parsing errors',
      'Ensure proper tag nesting',
      'Use unique ID attributes',
      'Close all tags properly',
    ],
    commonViolations: [
      'Duplicate ID attributes',
      'Improperly nested elements',
      'Missing closing tags',
      'Invalid attribute values',
    ],
  },
  '4-1-2-name-role-value': {
    number: '4.1.2',
    name: 'Name, Role, Value',
    level: 'A',
    principle: 'Robust',
    guideline: 'Compatible',
    description: 'UI components have appropriate names, roles, states, and values for assistive technologies.',
    whyItMatters: 'Screen readers need this information to convey the purpose and state of controls.',
    howToFix: [
      'Use native HTML elements where possible',
      'Add appropriate ARIA attributes to custom components',
      'Ensure accessible names for all controls',
      'Update states dynamically (aria-expanded, etc.)',
    ],
    commonViolations: [
      'Custom buttons without role="button"',
      'Missing accessible names on icon buttons',
      'States not communicated (expanded, checked)',
      'Custom controls without keyboard support',
    ],
  },
} as const;

export type IndustryKey = keyof typeof industries;
export type PlatformKey = keyof typeof platforms;
export type CountryKey = keyof typeof euCountries;
export type WcagCriterionKey = keyof typeof wcagCriteria;
